### ISSUE TITLE
Invalid negative coordinate handling

### ISSUE THREAD

**Issue by andyzukunft** [kpym/hist2geo#1]
Hey Kroum,

at first I want to thank you for your handy tool. It helped me a lot. On top of that it's incredibly fast.

I encountered an issue with negative Longitude handling. I have been to London in 2019 and used the *Google Takeout* export to tag some photos with *PhotoLocator*. However there have been two issues
1. Some export entries have been invalid in both .gpx and .kml. The Location "tag" just wasn't closed / something interrupted the code at this position.
2. Provided negative longitude where displayed as ".-123" instead "-.123". At least I assume it's just a wrong placement and not a complete incorrect conversion. Might also be an issue with the Google GPS data.

In addition I think the output of ".123" values is sub-optimal. In my opinion it would be best to always prefix a zero "0.123" or "-0.123" to reduce possible parsing issues with other libraries.

Correct negative values (gpx)
```
<trkpt lat="51.5023747" lon="-.1555234">
    <time>2019-04-23T11:03:04.707Z</time>
    <accuracy>16</accuracy>
</trkpt>
```

Invalid negative values (gpx)
```xml
<trkpt lat="51.5088310" lon=".-784647">
    <time>2019-04-23T13:52:03Z</time>
    <accuracy>3</accuracy>
</trkpt>
```

Invalid node (gpx)
```xml
<trk>
    <trkseg>
        <trkpt lat="51.4861638" lon="
    </trkseg>
</trk>
<trk>
  <trkseg>
    <trkpt lat="51.4815525" lon="-.3519142">
        <time>2019-04-21T08:42:04.060Z</time>
        <accuracy>16</accuracy>
    </trkpt>
        <trkpt lat="51.4817621" lon="-.3516580">
        <time>2019-04-21T08:42:27.076Z</time>
        <accuracy>17</accuracy>
    </trkpt>
  </trkseg>
</trk>
```

**Comment by kpym** [comment]
Hi Andy,
Thank you for reporting this issue. 🙏 
I've identified and corrected the error, I hope. 
Could you please verify if the latest release [v0.7.2](https://github.com/kpym/gotoextr/releases/tag/v0.7.2) resolves the problem as expected?

**Comment by andyzukunft** [comment]
As far as I can tell the mentioned problem has been fixed. The values are no longer invalid and values around zero are now "prefixed" with "0". This applies to gpx and kml files.

Example, same entries as "Invalid node" from above (gpx)
```xml
<trk>
  <trkseg>
    <trkpt lat="51.4861638" lon="0.0987594">
      <time>2019-04-21T08:41:36.739Z</time>
      <accuracy>16</accuracy>
    </trkpt>
  </trkseg>
</trk>
<trk>
  <trkseg>
    <trkpt lat="51.4815525" lon="-0.3519142">
      <time>2019-04-21T08:42:04.060Z</time>
      <accuracy>16</accuracy>
    </trkpt>
    <trkpt lat="51.4817621" lon="-0.3516580">
      <time>2019-04-21T08:42:27.076Z</time>
      <accuracy>17</accuracy>
    </trkpt>
  </trkseg>
</trk>
```
